# -*- coding: utf-8 -*-
"""2numpy_arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13xtEjNBEbZrpDahfIboUpwn5g9PvP2cX
"""

import numpy as np

#result=np.array([1,3,5,7,9])
#result=np.arange(1,10)
#result=np.arange(1,10,2)
#result=np.zeros(10)
#result=np.ones(10)
#result=np.linspace(0,100,5)
#result=np.random.randint(0,10)
#result=np.random.randint(20)
#result=np.random.randint(1,10,3)
#result=np.random.rand(5)
#result=np.random.randn(5)

'''
np_array=np.arange(50)
np_multi=np_array.reshape(5,10)  # 5x10 matrix
print(np_multi.sum(axis=1))
print(np_multi.sum(axis=0))
'''

rnd_nums=np.random.randint(1,100,10)
print(rnd_nums)
result=rnd_nums.max()
result=rnd_nums.min()
result=rnd_nums.mean()
result=rnd_nums.argmax() #index
result=rnd_nums.argmin() #index
print(result)