# -*- coding: utf-8 -*-
"""4numpyArraysOp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_rKLEukp162Sqh6w3eywau3kjOHUR90
"""

import numpy as np

numbers1=np.random.randint(10,100,6)
numbers2=np.random.randint(10,100,6)
print(numbers1)
print(numbers2)

result=numbers1+numbers2
result=numbers1+10
result=numbers1-numbers2
result=numbers1-10
result=numbers1*numbers2
result=numbers1*10
result=numbers1/10
result=np.sin(numbers1)
result=np.cos(numbers1)
result=np.sqrt(numbers1)
result=np.log(numbers1)

mnumbers1=numbers1.reshape(2,3)
mnumbers2=numbers2.reshape(2,3)


print(mnumbers1)
print(mnumbers2)

result=np.vstack((mnumbers1,mnumbers2))
result=np.hstack((mnumbers1,mnumbers2))
result=numbers1>=5
result=numbers1 % 2==0

print(result)

print(numbers1[result])