# -*- coding: utf-8 -*-
"""5numpyDemo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysEzSRhJowOBwe1bTn3-kME9GeyZh9s8
"""

import numpy as np

#create numpy array
arr1=np.array([10,15,30,45,60])
print(arr1)


arr2=np.arange(5,15)
print(arr2)

arr3=np.arange(50,100,5)
print(arr3)

arr4=np.ones(10)
print(arr4)

arr5=np.zeros(10)
print(arr5)

arr6=np.linspace(0,100,5)  #equal distance-linspace
print(arr6)

arr7=np.random.randint(10,30,5)
print(arr7)

arr8=np.random.randn(10)  #10 numbers between -1,+1
print(arr8)


matris=np.random.randint(-50,50,15).reshape(3,5)
'''
result=np.random.randint(10,50,15).reshape(3,5)

rowTotal=matris.sum(axis=1)
colTotal=matris.sum(axis=0)
print(matris)
print(rowTotal)
print(colTotal)


result=matris.max()
result=matris.min()
result=matris.mean()
result=matris.argmax()
result=matris.argmin()
'''

arr=np.arange(1,20)
print(arr)
result=arr[:3]

result=arr[::-1]  #reverse

result=matris[0]

result=matris[1,2]

result=matris[:,0] #all row's first element

result=matris**2

even=matris[matris % 2==0 ]
result=even[even>0]

print(result)